language: python
python:
    - "2.7"
    - "2.6"
install:
    - "pip install jinja2"
    - "pip install mock"
    - "pip install coverage"
    - "pip install coveralls --use-mirrors"
before_script:
    - "touch /tmp/test"
    - "sudo apt-get install -qq MySQLdb-python"
script:
    - "nosetests --with-coverage --cover-package=soy"
after_success: "coveralls"
